version: "3"
services:
  db:
    image: mysql
    env_file: .env
    ports:
      - 13306:3306

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: python main.py
    restart: on-failure
    env_file: .env
    ports:
      - 18000:8000

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm run start-dev
    restart: on-failure
    env_file: .env
    ports:
      - 19000:9000

  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
      - 10080:80
      - 10443:443
    depends_on:
      - backend
      - frontend
