version: "3"
services:
  db:
    image: mysql
    env_file: .env
    ports:
      - 13306:3306

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    command: python main.py
    restart: on-failure
    env_file: .env
    ports:
      - 18000:8000

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    command: node server.js
    restart: on-failure
    env_file: .env
    ports:
      - 19000:9000

  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
